# Generated by Django 3.2.6 on 2021-09-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soxapp', '0003_signal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='channel',
        ),
        migrations.AddField(
            model_name='game',
            name='away_record',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='feed_link',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='home_record',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='away_team',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team',
            field=models.CharField(max_length=25),
        ),
    ]
