# Generated by Django 3.2.6 on 2021-09-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soxapp', '0004_auto_20210911_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='type',
            field=models.CharField(default='Game Start', max_length=10),
            preserve_default=False,
        ),
    ]
