# Generated by Django 3.2.6 on 2021-09-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soxapp', '0005_signal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='official_date',
            field=models.DateField(default='2021-09-10'),
            preserve_default=False,
        ),
    ]
